---
abstract: 'creates Packages list and starts APT repository'
author:
  - 'Zdenek Bohunek <zed448@icloud.com>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.0401, CPAN::Meta::Converter version 2.150001'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Repo
no_index:
  directory:
    - t
    - inc
requires:
  Mojolicious: '7.01'
  perl: '5.01'
version: '0.09'
